spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  config:
    import: confidential.yml

server:
  port: 8080
  servlet:
    context-path: /notification_service
    encoding:
      charset: UTF-8
      force: true





