version: '3.5'
services:
  db:
    build: postgresql
    image: taskmanager_postgresql:1.0.0
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
      - taskmanager_ntwrk
  pgadmin:
    build: pgadmin
    image: taskmanager_pgadmin:1.0.0
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "82:80"
    networks:
      - taskmanager_ntwrk
  swagger-ui:
    build: swagger-ui
    image: taskmanager_swagger-ui:1.0.0
    ports:
      - "81:8080"
    networks:
      - taskmanager_ntwrk

  user-service:
    depends_on:
    - db
    build: user-service
    image: taskmanager_user-service:1.0.0
    networks:
      - taskmanager_ntwrk
    environment:
      spring.datasource.url: jdbc:postgresql://db:5432/user_service?ApplicationName=User_Service
      spring.datasource.username: root
      spring.datasource.password: root
      app.network.user_service.address: user-service:8080
      app.network.audit_service.address: audit-service:8080
      app.network.notification_service.address: notification-service:8080

  audit-service:
    depends_on:
      - db
    build: audit-service
    image: taskmanager_audit-service:1.0.0
    networks:
      - taskmanager_ntwrk
    environment:
      spring.datasource.url: jdbc:postgresql://db:5432/audit_service?ApplicationName=Audit_Service
      spring.datasource.username: root
      spring.datasource.password: root

  proxy:
    build: proxy
    image: taskmanager_proxy:1.0.0
    ports:
      - "80:80"
    networks:
      - taskmanager_ntwrk
networks:
    taskmanager_ntwrk:
      name: taskmanager_ntwrk