spring:
  jpa:
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:19092


  datasource:
    url: jdbc:postgresql://localhost:5432/user_service?ApplicationName=User_Service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: app
  jackson:
    property-naming-strategy: SNAKE_CASE

logging:
  file:
    name: user_service
    path: logs/

  level:
    org:
      hibernate:
        SQL:
          DEBUG
        orm:
          jdbc:
            bind:
              Trace

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
app:
  network:
    user_service:
      host: localhost
      appendix: /api/v1/users
      internal_appendix: /internal
    audit_service:
      address: localhost:81
      host: localhost:81
      appendix: /audit
    notification_service:
      address: localhost:82
      host: localhost:82
      appendix: /notification_service/email

jwt:
  secret: ucHYIsBgrm/XpThkkMBk4uaEl/8Es4VXSM85QcopGhk=
  issuer: Ilya




