spring:
  jpa:
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092



  datasource:
    url: jdbc:postgresql://localhost:5432/user_service?ApplicationName=User_Service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: app
  jackson:
    property-naming-strategy: SNAKE_CASE


logging:
  level:
    org:
      hibernate:
        SQL:
          DEBUG
        orm:
          jdbc:
            bind:
              Trace

server:
  port: 8080
  servlet:
    context-path: /user_service
    encoding:
      charset: UTF-8
      force: true
app:
  network:
    user_service:
      address: localhost:8080
      host: localhost
      appendix: /user_service/api/v1/users
    audit_service:
      address: localhost:81
      host: localhost:81
      appendix: /audit_service/api/v1/audit
    notification_service:
      address: localhost:82
      host: localhost:82
      appendix: /notification_service/api/v1/email

jwt:
  secret: ucHYIsBgrm/XpThkkMBk4uaEl/8Es4VXSM85QcopGhk=
  issuer: Ilya




