spring:
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/task_service?ApplicationName=Task_Service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: app
  jackson:
    property-naming-strategy: SNAKE_CASE


logging:
  level:
    org:
      hibernate:
        SQL:
          DEBUG
        orm:
          jdbc:
            bind:
              Trace

server:
  port: 8080
  servlet:
    context-path: /task_service
    encoding:
      charset: UTF-8
      force: true
app:
  network:
    user_service:
      address: localhost:8080
      host: localhost
      appendix: /user_service/api/v1/users
      internal_appendix: /user_service/internal

jwt:
  secret: ucHYIsBgrm/XpThkkMBk4uaEl/8Es4VXSM85QcopGhk=
  issuer: Ilya




